name = "fitness-realtors"
main = "worker.js"
compatibility_date = "2026-03-16"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
RESEND_FROM_EMAIL = "Fitness Realtors <noreply@fitnessrealtors.com>"

[[d1_databases]]
binding = "DB"
database_name = "commision-calculator"
database_id = "55dc004d-3a29-45dc-9976-738270dd35d4"
