name = "fitness-realtors"
main = "worker.js"
compatibility_date = "2026-03-16"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "commision-calculator"
database_id = "55dc004d-3a29-45dc-9976-738270dd35d4"
